-- Ads 테이블 생성
CREATE TABLE ads (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    type ENUM('sponsor', 'salon') NOT NULL,
    salon_id BIGINT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (salon_id) REFERENCES salons (id) ON DELETE SET NULL
);

-- Ad Media 테이블 생성
CREATE TABLE ad_medias (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ad_id BIGINT NOT NULL,
    url VARCHAR(255) NOT NULL,
    type ENUM('image', 'video') NOT NULL,
    `order` INTEGER NOT NULL DEFAULT 0,
    duration INTEGER NOT NULL DEFAULT 30,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    size ENUM('min', 'max') NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ad_id) REFERENCES ads (id) ON DELETE CASCADE
);

-- Ad Schedules 테이블 생성
CREATE TABLE ad_schedules (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ad_id BIGINT NOT NULL,
    time TIME NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ad_id) REFERENCES ads (id) ON DELETE CASCADE
);

-- Ad Locations 테이블 생성
CREATE TABLE ad_locations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ad_id BIGINT NOT NULL,
    target_type ENUM('nationwide', 'administrative') NOT NULL,
    city VARCHAR(100),
    district VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ad_id) REFERENCES ads (id) ON DELETE CASCADE
);

-- Ad Campaigns 테이블 생성
CREATE TABLE ad_campaigns (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ad_id BIGINT NOT NULL,
    budget DECIMAL(10,2) NOT NULL,
    daily_budget DECIMAL(10,2),
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ad_id) REFERENCES ads (id) ON DELETE CASCADE
);